import os

AZURE_CONNECTION_STRING = os.getenv('GATHER_CONTAINER_CONNECTION_STRING')
INPUT_CONTAINER_NAME = os.getenv('GATHER_CONTAINER_NAME')
OUTPUT_CONTAINER_NAME = os.getenv('FIND_CHUNKS_CONTAINER_NAME')